version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-test-app
    ports:
      - "27017:27017"
      - "27018:27018"
    volumes_from:
      - mongodbdata

  mongodbdata:
    image: tianon/true
    container_name: mongodb-data
    volumes:
      - /data/db

  app:
    build: .
    container_name: express-test-app
    hostname: express-mongo
    mem_limit: "2G"
    memswap_limit: "2G"
    cpuset: "2"
    ports:
    - "13000:3000"
    restart: on-failure
    privileged: true
    depends_on:
      - mongodb
    links:
      - mongodb
    dns:
      - 8.8.8.8
      - 8.8.4.4
    tty: true
    volumes:
      - "./:/usr/src/app"